
'use client';

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { LifeBuoy, Mail, Bug, MessageSquare, Loader2 } from "lucide-react";
import { useUserProfile } from "@/hooks/use-user-profile";
import { useUser, addDocumentNonBlocking } from "@/firebase";
import { useViewAs } from "@/hooks/use-view-as";
import { Button } from "@/components/ui/button";
import Image from 'next/image';
import { useState } from "react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { collection, serverTimestamp } from "firebase/firestore";
import { useFirestore } from "@/firebase";
import { createAlert } from "@/ai/flows/create-alert-flow";

const feedbackSchema = z.object({
  description: z.string().min(15, { message: "Please provide a detailed description." }),
});
type FeedbackFormData = z.infer<typeof feedbackSchema>;

function FeedbackDialog({ type, onOpenChange }: { type: 'Bug' | 'Feature', onOpenChange: (open: boolean) => void }) {
  const { user } = useUser();
  const { profile } = useUserProfile(user);
  const firestore = useFirestore();
  const { toast } = useToast();

  const { register, handleSubmit, formState: { errors, isSubmitting }, reset } = useForm<FeedbackFormData>({
    resolver: zodResolver(feedbackSchema),
  });

  const onSubmit = async (data: FeedbackFormData) => {
    if (!user || !profile || !firestore) {
      toast({ variant: 'destructive', title: 'Not Logged In' });
      return;
    }

    const feedbackData = {
      type: type.toLowerCase() as 'bug' | 'feature',
      description: data.description,
      userId: user.uid,
      userName: profile.name,
      status: 'New',
      timestamp: serverTimestamp(),
    };

    try {
      await addDocumentNonBlocking(collection(firestore, 'ai-feedback'), feedbackData);
      toast({
        title: `${type} Report Submitted!`,
        description: "Thank you for your feedback. The team has been notified.",
      });

      // Notify management
      const managementRoles = ['Executive Director', 'Administrator'];
      await createAlert({
          type: 'Urgent',
          priority: 'Medium',
          message: `A new ${type.toLowerCase()} report has been submitted by ${profile.name}.`,
          action: '/management/feedback', // This page would need to be created
          creatorId: user.uid
      });

      reset();
      onOpenChange(false);
    } catch (e: any) {
      console.error(`Failed to submit ${type} report`, e);
      toast({
        variant: 'destructive',
        title: 'Submission Failed',
        description: e.message || `Could not save your ${type.toLowerCase()} report.`,
      });
    }
  };

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
      <div className="space-y-2">
        <Label htmlFor="description">Please describe the {type.toLowerCase()} in detail:</Label>
        <Textarea
          id="description"
          placeholder={type === 'Bug' ? 'e.g., "When I click the save button on the expenses page, nothing happens..."' : 'e.g., "It would be great if the dashboard showed a summary of..."'}
          className="min-h-[150px]"
          {...register('description')}
        />
        {errors.description && <p className="text-sm text-destructive">{errors.description.message}</p>}
      </div>
      <Button type="submit" disabled={isSubmitting}>
        {isSubmitting && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
        Submit {type} Report
      </Button>
    </form>
  )
}

const ExecutiveDirectorManual = () => (
    <div className="prose dark:prose-invert max-w-full">
        <p>Welcome to the 30,000-foot view. As the Executive Director, your dashboard and management tools are configured to give you a strategic, real-time command center for the entire organization.</p>

        <hr />

        <h3>1. Your Executive Dashboard: The Mission Control</h3>
        <p>Your dashboard is designed for high-level oversight and quick decision-making. It consolidates the most critical organizational data into one place.</p>
        
        <h4>Key Components:</h4>
        <ul>
            <li><strong>Team Performance Leaderboard:</strong> Instantly see which team members are generating the most value this month based on their logged activities. This helps you identify top performers and recognize contributions.</li>
            <li><strong>Ecosystem Pulse:</strong> Monitor the health of our Inspire-Equip-Sustain model. This card shows you how many programs are active (Inspire), how many youth activities are running (Equip), and the total value generated by our sustainable initiatives (Sustain).</li>
            <li><strong>Key Results Tracker:</strong> This is your primary tool for strategic oversight. It shows live progress against the currently active operational plan (e.g., November Plan). The progress rings instantly tell you which objectives are on track and which are falling behind.</li>
            <li><strong>Team Deployment:</strong> See who has checked in today and what their primary mission is. This gives you a real-time sense of the team's focus and capacity.</li>
            <li><strong>Financial Queue:</strong> A critical action item. This card shows you all expense reports that are 'Pending' or 'Approved' and are waiting for your action. You can approve, reject, or mark items as disbursed directly from here, keeping the financial workflow moving.</li>
        </ul>

        <hr />

        <h3>2. Strategic Management Tools: Steering the Ship</h3>
        <p>The "Management" section in the sidebar is your toolbox for steering the organization. Here are the most critical modules for your role:</p>

        <h4>Operational Plan Updater (/management/operational-plan)</h4>
        <p>This is one of the most powerful tools at your disposal. At the beginning of a new month or quarter, you can paste the entire text of a new operational plan into this tool. The AI will read it, extract all the Key Results (KRs), and automatically update the goals for the entire application. This instantly re-aligns all dashboards and reporting. <strong>Use this tool to set the direction for the entire team in minutes.</strong></p>

        <h4>Finance & Expenses (/management/finance, /management/expenses)</h4>
        <p>Go here for a complete financial overview. The <strong>Finance</strong> page provides a full cashbook (income vs. expense), while the <strong>Expenses</strong> page allows you to review the entire history of all expense reports, see their status, and take action.</p>
        
        <h4>User Management (/management/users)</h4>
        <p>As the administrator, you can change the roles of any user in the system. This immediately changes their dashboard and permissions, giving them access to the tools they need for their new responsibilities.</p>

        <hr />

        <h3>3. Your AI Coach: Your Strategic Advisor</h3>
        <p>Your AI Coach is not just for simple questions. Use it for high-level strategic analysis and summaries.</p>
        <ul>
            <li><strong>"Summarize all team activity from yesterday."</strong></li>
            <li><strong>"What is the total value generated by the RED Campaign this month?"</strong></li>
            <li><strong>"Draft a project update for the board based on the latest data."</strong></li>
            <li><strong>"Who are our top 3 most engaged partners this month?"</strong></li>
        </ul>
        <p>Your conversations are private. Use the AI to get quick insights without having to manually dig through data.</p>
        
        <hr />

        <p>This application is designed to give you leverage. By ensuring your team uses it consistently for check-ins, activity logging, and expense reporting, you guarantee that your dashboard is always giving you a true, real-time picture of the organization's health and performance.</p>
    </div>
);


const InternVolunteerManual = () => (
    <div className="prose dark:prose-invert max-w-full">
        <p>Welcome to the Omuto Foundation family! We are thrilled to have you on board. This guide will help you get started with Omuto Central, our all-in-one application designed to make your work impactful, efficient, and connected to the rest of the team.</p>

        <hr />

        <h3>1. Your Dashboard: Your Mission Control</h3>
        <p>When you log in, you'll land on your personal dashboard. Think of this as your daily mission control.</p>
        
        <Image src="https://i.imgur.com/AuhF19l.jpeg" alt="Your Dashboard" width={800} height={450} className="rounded-lg border" data-ai-hint="dashboard screenshot" />

        <p>Here you will find:</p>
        <ul>
            <li><strong>A Warm Welcome:</strong> A greeting to get your day started.</li>
            <li><strong>Smart Reminders:</strong> Your AI Coach will analyze your pending tasks and calendar events to give you smart, actionable reminders for the day. This helps you stay on track and focus on what matters most.</li>
            <li><strong>Quick Actions:</strong> A set of buttons for the most common tasks you'll perform.</li>
        </ul>

        <hr />

        <h3>2. Your Daily Rhythm: The End-of-Day Note</h3>
        <p>Your most important daily task is to submit your end-of-day note. This is how your supervisor and the rest of the team see your progress and learnings.</p>
        <ul>
            <li><strong>How:</strong> Click "Submit End-of-Day Note" from your dashboard or find the form in the "Forms Hub".</li>
            <li><strong>What to Write:</strong> The form is simple. Just describe what you accomplished and one new thing you learned. That's it!</li>
            <li><strong>Why:</strong> This keeps everyone in sync and helps us celebrate your contributions and growth! It's a key part of our culture of learning.</li>
        </ul>
        
        <hr />

        <h3>3. Your AI Coach: Your Personal Assistant</h3>
        <p>You have a powerful AI assistant available 24/7. Use it for anything and everything!</p>
        <ul>
            <li><strong>How to Access:</strong> Click on the <strong>AI Coach</strong> link in the sidebar.</li>
            <li><strong>What to Ask:</strong>
                <ul>
                    <li>"Can you explain what the RED Campaign is?"</li>
                    <li>"Who is the lead for the GreenSchools program?"</li>
                    <li>"Summarize the team's activity from yesterday."</li>
                    <li>"Help me brainstorm ideas for a social media post about our recent field visit."</li>
                </ul>
            </li>
        </ul>
        <p>Your conversations with the AI Coach are <strong>private</strong>. Don't hesitate to use it to get up to speed on projects, understand terminology, or even help you draft messages.</p>

        <hr />

        <h3>4. Your Profile & Tasks: Staying Organized</h3>
        <p>Your profile is your personal space within Omuto Central.</p>
        <ul>
            <li><strong>How to Access:</strong> Click on your avatar in the top-right corner and select "Profile," or use the "Profile" link in the navigation.</li>
            <li><strong>Features:</strong>
                <ul>
                    <li><strong>Update Your Picture:</strong> Click on your avatar to upload a new profile picture.</li>
                    <li><strong>Manage Your Tasks:</strong> Switch to the "Task Management" tab to see your personal to-do list. You can add new tasks to keep yourself organized. As you complete them, check them off!</li>
                </ul>
            </li>
        </ul>

        <hr />

        <h3>5. The Team Hub: Staying Connected</h3>
        <p>Even when working remotely, it's important to stay connected. The Team Hub section is where this happens.</p>
        <ul>
            <li><strong>Team Space:</strong> A group chat for all team members. Share quick updates, ask questions, and celebrate wins together.</li>
            <li><strong>Team Calendar:</strong> A shared calendar showing all upcoming events, meetings, and important deadlines. Check this regularly to know what's happening.</li>
            <li><strong>Check-in & Check-out Streams:</strong> These are live feeds of the daily plans (check-ins) and end-of-day reports (check-outs) from the entire team. It's a great way to see what everyone is working on and learn from their progress.</li>
        </ul>

        <hr />

        <p>We are so excited to see the amazing contributions you will make. If you ever feel stuck, your first point of contact should be your supervisor, and your second should be your AI Coach! Welcome aboard.</p>
    </div>
);

const ProgramManagerManual = () => (
    <div className="prose dark:prose-invert max-w-full">
        <h2>Program & Partnerships Manager Guide</h2>
        <p>As a Program & Partnerships Manager, your role is to oversee the health of our programs and cultivate strong relationships. Omuto Central is designed to give you the tools for strategic oversight.</p>
        <hr />
        <h3>1. Your Dashboard: Program & Pipeline Health</h3>
        <ul>
            <li><strong>Key Results Tracker:</strong> Monitor progress against strategic objectives. Use this to ensure your programs are aligned with our quarterly goals.</li>
            <li><strong>Team Deployment:</strong> See which team members have checked in and what their focus is for the day. This helps you understand team capacity and allocation.</li>
            <li><strong>Partnership Pipeline:</strong> A snapshot of your engagement with partners. It highlights urgent action items (like overdue reports) and upcoming meetings, ensuring you never miss a follow-up.</li>
            <li><strong>Quick Insights:</strong> A chart showing the trend of field activities over the past few weeks, helping you spot momentum or slowdowns.</li>
        </ul>
        <hr />
        <h3>2. Core Workflows</h3>
        <h4>Managing Programs (/management/programs)</h4>
        <p>This is where you define and track all core initiatives. You can add new programs, update their status (e.g., from 'On Track' to 'At Risk'), and define their key objectives. This data directly feeds into the dashboards and the ROI Calculator.</p>
        <h4>Managing Partnerships (/management/partnerships)</h4>
        <p>Your central CRM. Use the Kanban board to drag-and-drop partners through the pipeline (Prospecting → Negotiation → Active). Click on any partner to log meetings, perform health checks, and update their 'Next Step', which automatically updates your dashboard alerts.</p>
        <h4>Approving Expenses (/management/expenses)</h4>
        <p>As a manager, you are responsible for approving or rejecting expense reports submitted by your team. You will receive notifications for pending reports, and you can approve them directly from the main Expenses page or the Financial Queue on your dashboard.</p>
        <hr />
        <h3>3. AI Coach for Program Strategy</h3>
        <p>Leverage your AI Coach for strategic analysis and content creation:</p>
        <ul>
            <li><strong>"Summarize all activities related to the RED Campaign in the last month."</strong></li>
            <li><strong>"Draft a brief partnership proposal for a potential education partner."</strong></li>
            <li><strong>"What are the most common challenges the team has logged for the GreenSchools program?"</strong></li>
        </ul>
    </div>
);

const OperationsManagerManual = () => (
    <div className="prose dark:prose-invert max-w-full">
        <h2>Operations & Field Manager Guide</h2>
        <p>As the Operations & Field Manager, your focus is on execution, logistics, and team efficiency. Omuto Central helps you keep the engine of the foundation running smoothly.</p>
        <hr />
        <h3>1. Your Dashboard: Field & Team Oversight</h3>
        <ul>
            <li><strong>Team Deployment:</strong> Your most important tool. See exactly who is on the ground, what their mission is, and what they are currently working on.</li>
            <li><strong>Quick Insights:</strong> Monitor the velocity of field activities to ensure the team is maintaining operational tempo.</li>
            <li><strong>Dashboard Calendar:</strong> Keep track of all upcoming field visits, events, and deadlines to manage logistics effectively.</li>
            <li><strong>Approval Queue:</strong> Approve expense reports submitted by field staff to unblock their financial needs quickly.</li>
        </ul>
        <hr />
        <h3>2. Core Workflows</h3>
        <h4>Managing Projects (/management/projects)</h4>
        <p>This is where you track specific, time-bound initiatives. Define projects, assign managers, and update their completion percentage to keep stakeholders informed.</p>
        <h4>Managing Equipment (/management/equipment)</h4>
        <p>Use this module as your asset inventory. Track who has which piece of equipment (cameras, projectors, etc.), its condition, and its status. This is crucial for planning field visits.</p>
        <h4>Managing Workplans (/management/workplans)</h4>
        <p>Create and publish the official team-wide plan for the week. This sets the priorities that every team member will see on their "My Weekly Plan" page and use as a basis for their daily check-ins.</p>
        <hr />
        <h3>3. AI Coach for Operational Efficiency</h3>
        <p>Use your AI Coach to streamline planning and reporting:</p>
        <ul>
            <li><strong>"Create a checklist for a standard community entry visit."</strong></li>
            <li><strong>"Summarize all checkouts from yesterday. Who reported blockers?"</strong></li>
            <li><strong>"Who is holding the Canon C70 camera right now?"</strong></li>
        </ul>
    </div>
);

const MediaFinanceManual = () => (
    <div className="prose dark:prose-invert max-w-full">
        <h2>Media & Finance Lead Guide</h2>
        <p>Your role bridges storytelling and financial stewardship. Omuto Central provides specialized tools to manage both sides of this crucial function.</p>
        <hr />
        <h3>1. Your Dashboard: The Media & Finance Hub</h3>
        <ul>
            <li><strong>Budget Health:</strong> A real-time view of your cash balance, monthly income, and monthly expenses. This is your primary financial snapshot.</li>
            <li><strong>Financial Queue:</strong> Your action center. This shows reports 'Pending Approval' (which you can approve if you are also a manager) and, more importantly, reports 'Awaiting Disbursement'. This is your to-do list for sending out money.</li>
            <li><strong>Media Opportunities:</strong> A feed of recent field activities where staff indicated they "Captured Content". This is your pipeline for new stories. Click "Generate Story" to use AI to draft a narrative based on the activity data.</li>
             <li><strong>Latest Testimonies:</strong> A feed of newly recorded video, audio, or text testimonies. Use the AI summaries and quotes to quickly find content for your communications.</li>
        </ul>
        <hr />
        <h3>2. Core Workflows</h3>
        <h4>Financial Management (/management/finance)</h4>
        <p>This is your complete cashbook. Log all incoming funds (grants, donations) and directly log operational expenses (like rent or utilities) that don't require a full report. It provides a full historical ledger.</p>
        <h4>Expense Management (/management/expenses)</h4>
        <p>Review, approve, and disburse all expense reports from the team. Filter by status to see what's pending, what's been approved, and what needs to be paid out.</p>
        <h4>Testimony Library & Impact Story (/testimonies, /impact-story)</h4>
        <p>This is your content engine. In the library, you can review all submitted testimonies. The AI automatically provides transcriptions, summaries, and key quotes. Use the Impact Story generator to turn raw activity data into compelling narratives for social media or reports.</p>
        <hr />
        <h3>3. AI Coach for Content & Analysis</h3>
        <p>Your AI coach is a powerful assistant for both finance and media:</p>
        <ul>
            <li><strong>"What was our biggest expense category last month?"</strong></li>
            <li><strong>"Write three social media posts based on the latest testimony from Jane."</strong></li>
            <li><strong>"Summarize the financial performance for Q3."</strong></li>
        </ul>
    </div>
);

const ResourceMobilizationManual = () => (
    <div className="prose dark:prose-invert max-w-full">
        <h2>Resource Mobilization Lead Guide</h2>
        <p>Your goal is to build the financial and strategic partnerships that fuel Omuto's mission. Omuto Central is your toolkit for discovery, tracking, and proposal writing.</p>
        <hr />
        <h3>1. Core Tools for Fundraising</h3>
        <h4>AI Grant Discovery (/resources)</h4>
        <p>This is your starting point for finding new funding. Enter keywords (e.g., "youth empowerment uganda", "environmental grants africa") and the AI will search for relevant opportunities. You can then add promising grants directly to your Proposal Tracker with one click.</p>
        <h4>Proposal Tracker (/resources)</h4>
        <p>This table tracks every grant proposal you are working on. Update the status from 'Draft' to 'Submitted' to 'Approved' to maintain a clear view of your funding pipeline.</p>
        <h4>Donor Directory & Partnership Pipeline (/management/partnerships)</h4>
        <p>Your central CRM. Manage relationships with active donors in the Directory and track potential new funders in the Pipeline. Log meetings and health checks to maintain strong relationships.</p>
        <hr />
        <h3>2. AI-Powered Proposal Writing</h3>
        <p>Omuto Central's AI is trained on our organizational knowledge base. Use it to dramatically speed up your writing process.</p>
        <ul>
            <li><strong>From the Proposal Tracker:</strong> When you add a new proposal, you can use the AI to draft a concept note. (Functionality coming soon).</li>
            <li><strong>From the AI Coach:</strong> Use the coach to generate specific sections for your proposals.
                <ul>
                    <li>"Draft a problem statement about menstrual health challenges for rural girls in Uganda."</li>
                    <li>"Write a section describing Omuto's 'Ecosystem Model' for a grant application."</li>
                    <li>"Based on our logged activities, what are our most impressive quantitative impacts from the last quarter?"</li>
                </ul>
            </li>
        </ul>
        <hr />
        <h3>3. Key Dashboards</h3>
        <ul>
            <li><strong>Key Results Tracker:</strong> Understand the organization's current strategic priorities to ensure your proposals are aligned.</li>
            <li><strong>Partnership Pipeline:</strong> Get a quick snapshot of your most urgent follow-ups and upcoming partnership meetings.</li>
        </ul>
    </div>
);

const FieldCoordinatorManual = () => (
    <div className="prose dark:prose-invert max-w-full">
        <h2>Field Coordinator Guide</h2>
        <p>As a Field Coordinator, you are the backbone of our community impact. Omuto Central is designed to make your daily planning, execution, and reporting as simple and effective as possible.</p>
        <hr />
        <h3>1. Your Daily Rhythm</h3>
        <h4>AI Daily Planner (/daily-plan)</h4>
        <p>Start your day here. Tell the AI your main goal, and it will generate a strategic schedule for you, helping you break down big tasks and connect them to our wider objectives. After you review the plan, submit it as your official "Check-in".</p>
        <h4>ROI Activity Form (/forms/activity)</h4>
        <p>This is your primary tool for reporting. Before you start an activity, use the "Planning" tab to estimate costs and value. After the activity, fill out the "Logging" tab with the final numbers and a brief story about a memorable moment. This is crucial for showing our impact.</p>
        <h4>Daily Check-out (/forms/check-out)</h4>
        <p>At the end of the day, use this simple form to report on which tasks from your daily plan you completed, share what you learned, and state your priority for tomorrow. This keeps the whole team in sync.</p>
        <hr />
        <h3>2. Your Dashboard: Your Mission Control</h3>
        <ul>
            <li><strong>Team Deployment:</strong> See which other team members are in the field and what they are working on.</li>
            <li><strong>Team Pulse:</strong> A live feed of the latest end-of-day reports (check-outs) from the entire team. A great way to learn from others' experiences.</li>
            <li><strong>My Weekly Plan:</strong> See the high-level priorities set by management for the week, and add your own tasks to create your personal workplan.</li>
            <li><strong>Dashboard Calendar:</strong> Check for upcoming field visits, community events, or important deadlines.</li>
        </ul>
        <hr />
        <h3>3. Key Tools for Field Work</h3>
        <h4>Record Testimony (/record-testimony)</h4>
        <p>Capture a powerful story directly from a beneficiary using your phone's camera or microphone. The AI will automatically transcribe the recording and pull out key quotes, saving you hours of work.</p>
        <h4>AI Coach (/chat)</h4>
        <p>Your 24/7 assistant. Use it for anything:</p>
        <ul>
            <li>"What is the phone number for the headteacher at St. Mary's?"</li>
            <li>"Give me three icebreaker ideas for a community meeting."</li>
            <li>"Summarize Omuto's key talking points about the RED Campaign."</li>
        </ul>
    </div>
);

const DefaultManual = () => (
    <div className="prose dark:prose-invert max-w-full">
        <p>Welcome to Omuto Central! This is your central hub for all things Omuto Foundation.</p>
        <p>This guide is tailored to your role. Use it to understand your key dashboards and workflows. If you have any questions, don't hesitate to ask your supervisor or your AI Coach.</p>
    </div>
)

const AdministratorManual = () => (
     <div className="prose dark:prose-invert max-w-full">
        <h2>Administrator Guide</h2>
        <p>As an Administrator, you have the highest level of access and are responsible for maintaining the system's integrity and ensuring all team members can work effectively.</p>
        <hr/>
        <h3>1. Your Primary Responsibility: User Management</h3>
        <h4>User Roles Page (/management/users)</h4>
        <p>This is your most important tool. From here, you can assign and change the role of any user in the system. Changing a user's role will instantly update their dashboard, navigation, and permissions. Use this to onboard new staff or adjust responsibilities as roles evolve.</p>
        <hr/>
        <h3>2. System Oversight</h3>
        <p>Your dashboard and navigation give you access to all management modules. Your key tasks include:</p>
        <ul>
            <li><strong>Monitoring Team Activity:</strong> Use the <strong>Team Deployment</strong> and <strong>Team Pulse</strong> dashboards to ensure everyone is checking in and logging their work.</li>
            <li><strong>Overseeing Finances:</strong> You have full access to the <strong>Finance</strong> ledger and <strong>Expenses</strong> approval system.</li>
            <li><strong>Supporting Management:</strong> You can assist other managers by adding or updating programs, projects, partnerships, and other key data as needed.</li>
        </ul>
        <hr/>
         <h3>3. The "View As" Feature</h3>
         <p>In the top header bar, you will find an "eye" icon. This is the **View As** feature, which is exclusive to management and administrative roles. It allows you to temporarily view the entire application as if you were another role (e.g., "Field Coordinator"). This is incredibly powerful for:</p>
        <ul>
            <li><strong>Troubleshooting:</strong> If a user reports an issue, you can switch to their role to see exactly what they are seeing.</li>
            <li><strong>Training:</strong> You can use it to guide a new team member through their specific dashboard and tools.</li>
        </ul>
        <p>To exit "View As" mode, simply click the "Return to your own view" button in the yellow banner at the top of the screen.</p>
    </div>
)


export default function HelpPage() {
    const { user } = useUser();
    const { profile } = useUserProfile(user);
    const { viewAsRole } = useViewAs();
    const [isBugDialogOpen, setIsBugDialogOpen] = useState(false);
    const [isFeatureDialogOpen, setIsFeatureDialogOpen] = useState(false);


    const effectiveRole = viewAsRole || profile?.role;

    const renderManual = () => {
        switch (effectiveRole) {
            case 'Intern':
            case 'Volunteer':
                return <InternVolunteerManual />;
            case 'Executive Director':
                return <ExecutiveDirectorManual />;
            case 'Programs & Partnerships Manager':
                return <ProgramManagerManual />;
            case 'Operations & Field Manager':
                return <OperationsManagerManual />;
            case 'Media & Finance Lead':
            case 'Media & Communications Lead':
                return <MediaFinanceManual />;
            case 'Resource Mobilization Lead':
                return <ResourceMobilizationManual />;
            case 'Field Coordinator':
                return <FieldCoordinatorManual />;
            case 'Administrator':
                return <AdministratorManual />;
            default:
                return <DefaultManual />;
        }
    }

    return (
        <div className="flex flex-col gap-6">
            <header>
                <h1 className="font-headline text-3xl font-bold tracking-tight flex items-center gap-2">
                    <LifeBuoy className="h-8 w-8" />
                    Help & Support
                </h1>
                <p className="text-muted-foreground">
                    Your guide to making the most of Omuto Central.
                </p>
            </header>

            <Card>
                <CardHeader>
                    <CardTitle>User Manual for: {effectiveRole}</CardTitle>
                </CardHeader>
                <CardContent>
                    {renderManual()}
                </CardContent>
            </Card>

             <Card>
                <CardHeader>
                    <CardTitle>Need Assistance?</CardTitle>
                    <CardDescription>
                        Found a bug, have a question, or want to request a new feature? Let us know!
                    </CardDescription>
                </CardHeader>
                <CardContent className="flex flex-col sm:flex-row gap-4">
                     <Dialog open={isBugDialogOpen} onOpenChange={setIsBugDialogOpen}>
                        <DialogTrigger asChild>
                            <Button className="w-full sm:w-auto"><Bug className="mr-2 h-4 w-4" /> Report a Bug</Button>
                        </DialogTrigger>
                        <DialogContent>
                            <DialogHeader>
                                <DialogTitle>Report a Bug</DialogTitle>
                                <DialogDescription>Describe the issue you're encountering. The more detail, the better!</DialogDescription>
                            </DialogHeader>
                            <FeedbackDialog type="Bug" onOpenChange={setIsBugDialogOpen} />
                        </DialogContent>
                    </Dialog>
                     <Dialog open={isFeatureDialogOpen} onOpenChange={setIsFeatureDialogOpen}>
                        <DialogTrigger asChild>
                            <Button variant="outline" className="w-full sm:w-auto"><MessageSquare className="mr-2 h-4 w-4" /> Request a Feature</Button>
                        </DialogTrigger>
                        <DialogContent>
                            <DialogHeader>
                                <DialogTitle>Request a New Feature</DialogTitle>
                                <DialogDescription>Have an idea to make Omuto Central better? We'd love to hear it.</DialogDescription>
                            </DialogHeader>
                             <FeedbackDialog type="Feature" onOpenChange={setIsFeatureDialogOpen} />
                        </DialogContent>
                    </Dialog>
                </CardContent>
            </Card>
        </div>
    )
}

    